from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .fileutil import atomic_write
from .models import DiscoveredPlan

logger = logging.getLogger(__name__)


EXISTING_PLAN_DIRS: tuple[str, ...] = ("pending", "working", "reviewed", "reject")


@dataclass(frozen=True)
class ExistingPlanSummary:
    status: str
    keyword: str
    title: str
    timestamp_str: str  # YYYYMMDD_HHMMSS format for sorting by recency


def _parse_plan_filename(stem: str) -> tuple[str, str, str]:
    """Recover (keyword, title, timestamp_str) from a plan file stem.

    Save format is `<Keyword>__<YYYYMMDD>_<HHMMSS>_<safe-title>`.
    Falls back to ("Unassigned", stem, "") when the pattern doesn't match.
    The timestamp_str is in YYYYMMDD_HHMMSS format for lexicographic sorting.
    """
    if "__" in stem:
        keyword, rest = stem.split("__", 1)
        parts = rest.split("_", 2)
        if len(parts) >= 3:
            # parts[0] = YYYYMMDD, parts[1] = HHMMSS, parts[2] = safe-title
            timestamp_str = f"{parts[0]}_{parts[1]}"
            title = parts[2].replace("-", " ").strip() or stem
        else:
            # Malformed: no timestamp found
            timestamp_str = ""
            title = rest.replace("-", " ")
        return keyword or "Unassigned", title, timestamp_str
    return "Unassigned", stem.replace("-", " "), ""


def _is_translated_stem(stem: str) -> bool:
    parts = stem.rsplit(".", 1)
    return len(parts) == 2 and len(parts[1]) == 2


def scan_existing_plans(report_dir: Path) -> list[ExistingPlanSummary]:
    """Read filenames in pending/working/reviewed/reject and extract keyword+title.

    Does NOT open files — only globs filenames. Translated companions
    (`*.XX.md`) are skipped. Files that fail to parse are logged and skipped
    rather than causing a crash.

    If a directory cannot be read due to filesystem errors (permission denied,
    network timeout, I/O error), the directory is skipped with a warning and
    scanning continues with the remaining directories.
    """
    out: list[ExistingPlanSummary] = []
    for status in EXISTING_PLAN_DIRS:
        cat_dir = report_dir / status
        if not cat_dir.is_dir():
            continue
        try:
            plan_files = sorted(cat_dir.glob("*.md"))
        except OSError as e:
            # Directory scanning failed (permission denied, network timeout, etc.)
            # Log warning and continue with remaining directories
            logger.warning(
                "Failed to scan directory %s for existing plans: %s",
                cat_dir,
                e,
            )
            continue
        for f in plan_files:
            try:
                if _is_translated_stem(f.stem):
                    continue
                keyword, title, timestamp_str = _parse_plan_filename(f.stem)
                out.append(ExistingPlanSummary(
                    status=status,
                    keyword=keyword,
                    title=title,
                    timestamp_str=timestamp_str,
                ))
            except Exception as e:
                # Skip files that fail to parse, logging a warning
                logger.warning(
                    "Skipping plan file %s due to parse error: %s",
                    f,
                    e,
                )
    return out


def generate_markdown(
    plan: DiscoveredPlan, iteration: int, *, pending: bool = False
) -> str:
    """Generate a formatted markdown report for a plan."""
    now = datetime.now()
    status_label = (
        "Pending review (auto mode)" if pending else "Approved and saved by plan-finder"
    )

    files_list = "\n".join(f"- `{f}`" for f in plan.files_affected)
    steps_list = "\n".join(
        f"{i}. {step}" for i, step in enumerate(plan.implementation_steps, 1)
    )

    risks_section = ""
    if plan.risks:
        risks_list = "\n".join(f"- {r}" for r in plan.risks)
        risks_section = f"\n## Risks\n\n{risks_list}\n"

    keyword = (plan.keyword or "Unassigned").strip() or "Unassigned"

    return f"""\
# {plan.title}

> Generated by plan-finder on {now.strftime('%Y-%m-%d %H:%M:%S')}
> Iteration #{iteration} | Keyword: {keyword} | Category: {plan.category.value} | Priority: {["심각","매우 높음","높음","보통","낮음"][plan.priority-1]} | Effort: {plan.estimated_effort.value}

**Keyword:** `{keyword}`

## Description

{plan.description}

## Rationale

{plan.rationale}

## Files Affected

{files_list}

## Implementation Steps

{steps_list}
{risks_section}
---
*{status_label}*
"""


def save_plan(
    plan: DiscoveredPlan,
    iteration: int,
    report_dir: Path,
    *,
    pending: bool = False,
) -> Path:
    """Save a plan as a markdown file atomically. Returns the file path.

    If pending=True, saves to report_dir/pending/ instead of report_dir/.

    Uses atomic write (temp file + fsync + os.replace) to prevent corruption
    if the process crashes during the write operation.
    """
    target_dir = report_dir / "pending" if pending else report_dir
    target_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = (
        plan.title.lower().replace(" ", "-").replace("/", "-").replace("\\", "-")
    )
    safe_title = "".join(c for c in safe_title if c.isalnum() or c == "-")[:60]
    safe_title = safe_title.strip("-") or "untitled"

    raw_keyword = (plan.keyword or "").strip() or "Unassigned"
    safe_keyword = "".join(c for c in raw_keyword if c.isalnum())[:32] or "Unassigned"

    filename = f"{safe_keyword}__{timestamp}_{safe_title}.md"
    filepath = target_dir / filename

    content = generate_markdown(plan, iteration, pending=pending)
    atomic_write(filepath, content)

    return filepath
